add collection "Redes_sociales" and "Cargos"
CSIPro/csipro-cms pull request #3
Opened 2024-05-30 19:40 UTC by Kartleth

## Describe your changes

Agregar collections de "Redes_sociales" y "Cargos". Se modifico código en collection de "Miembros" para que se implementaran "Redes_socailes" y "Cargos" en esta. 

## Task URL (Asana, Jira, etc...)

_Provide url_

## What was done in this pull request

- [ ] Added A to create B.
- [ ] Refactored feature X to improve Y.
- [ ] ...

## Demo / Screenshot / Video

_Provide demo if possible_
![image](https://github.com/CSIPro/csipro-cms/assets/80503620/034ca551-63d4-4874-b64b-9497ccfa9c4b)

2024-05-30 21:01 UTC, saulprl requested changes
Un pequeño cambio y listo

2024-05-30 21:01 UTC, saulprl commented on src/collections/Cargos/index.ts
> +  slug: "cargos",
Hay que definir las `labels` como está hecho en la colección de `redes_sociales` para evitar que Payload lo infiera del `slug`

2024-06-03 22:35 UTC, Kartleth commented on src/collections/Cargos/index.ts
> +  slug: "cargos",
Listo, creo que faltarían en las que Luis agrego, las pongo también?

2024-06-03 22:40 UTC, saulprl approved these changes
LGTM :)

2024-06-08 20:15 UTC, merged